name: Feature Request
description: Suggest a new feature
labels: [Request]
body:
- type: markdown
  attributes:
  value: "# Feature Request Form"
- type: dropdown
  id: version
  attributes:
  label: Version
  description: What version of the Holster are you using?
  options:
  - v1.0.1
  - v1.0.0
  validations:
  required: true
- type: textarea
  id: desc
  attributes:
  label: Description
  description: Describe the feature you'd like to see implemented. Is your feature request related to a problem?
  validations:
  required: true
- type: textarea
  id: references
  attributes:
  label: References (optional)
  description: If applicable, add screenshots or videos to help explain your request.
  validations:
  required: false
- type: textarea
  id: misc
  attributes:
  label: Additional info (optional)
  description: Add any other context about the feature request here.
  validations:
  required: false
- type: checkboxes
  id: validation-check
  attributes:
  label: Please confirm the following:
  options:
    - label: I've checked for similar requests before opening this issue.
      required: true
- type: markdown
  attributes:
  value: "### Thank you very much for taking your time to fill out this report form."